name: Deploy to Cloud Run

on:
  push:
    branches: [ main, master ]  # Ana dallar üzerinde değişiklik olduğunda

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy keepsty-backend \
          --source . \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }} 